"""
OG Unity maker (Round 16) — OG builds downloadable Unity projects
for visitors, under Brent's approval flow (prepare -> approve ->
execute, the same rule as the Round 14 GitHub PR flow).

The flow, all inside the visitor's own chat thread:

1. ASK -> PLAN GATE. "make me a Unity game ..." claims a Unity job.
   OG answers with a plain-language PLAN only (what it is, the
   pieces/scripts, the controls, what's placeholder) ending in an
   explicit approval ask. A per-visitor pending state {stage: plan}
   is parked (60-minute expiry). NO cancels, tweaking the plan
   re-plans, drifting to another topic abandons the plan.
2. BUILD DRAFT. On YES, an instruction riding the established
   app-layer search seam (persona files are NEVER touched) makes the
   agent generate the whole project in-chat as strict file blocks:

       === PROJECT: <Name> ===
       === FILE: Assets/Scripts/PlayerController.cs ===
       <full file content>
       === END FILE ===

   and present a PREVIEW section (the file list + the honesty note)
   ending in "Reply YES to package it". Stage moves to preview.
   Change requests ("make the player faster") loop right here: the
   agent regenerates the full file set with the change applied and
   the preview is shown again. NOTHING is zipped at this stage.
3. PACKAGE ON APPROVAL. On the preview YES the module lifts the file
   blocks out of the visitor's OWN history (the Round 14 pattern —
   what was shown is what ships), validates and sanitizes them,
   writes the README itself (project name, "Generated by OG AI",
   Unity 2022.3 LTS target, open-in-Unity steps, and the honesty
   lines: AI-generated, NOT compiled or tested, placeholder art),
   guarantees ProjectSettings/ProjectVersion.txt (2022.3 LTS) and a
   minimal Packages/manifest.json when the draft lacks them, and
   zips. Only a successful package spends one unit of the per-tier
   "unity" cap (og_tiers kind "unity": free 1 / standard 3 / pro 10
   / blue 25 / blackout 100 per day). Plans, previews, revisions,
   declines and failures spend nothing; an at-cap visitor is told at
   the ASK stage. The ZIP is stored per-visitor for 24 h and served
   only to the owning ogai_uid cookie at GET /unity/download/<id>.
4. REVISIONS AFTER DOWNLOAD re-enter the preview loop from the
   packaged state: a fix ask regenerates the file set, the preview
   shows again, and a YES packages a NEW ZIP (a new version, one
   more unit).

Validation (fail safe — nothing packaged, nothing charged):
paths are sanitized (no "..", no absolute paths; files must live
under Assets/, ProjectSettings/ or Packages/, plus README.md at the
root — the module's own README always wins); extensions are
allowlisted (.cs .md .txt .json .asmdef); caps are <=40 files,
<=64 KB per file, <=512 KB total. Individual bad files are dropped;
zero valid files (or a total-size breach) packages nothing.

Pending state is process-local (like the Round 14 PR drafts): a
server restart inside the window drops an unapproved draft —
nothing was packaged, by design; the visitor just asks again.
"""

import logging
import os
import re
import threading
import time
import uuid
import zipfile
from datetime import datetime, timezone
from typing import Dict, List, Optional

from fastapi import HTTPException, Request
from fastapi.responses import FileResponse

logger = logging.getLogger(__name__)

UNITY_STORE_DIR = os.getenv("OG_UNITY_STORE_DIR", "unity_builds")
_PENDING_TTL = 60 * 60          # a plan/preview stays approvable 1 h
_ZIP_TTL = 24 * 60 * 60         # packaged ZIPs are kept 24 h
_MAX_FILES = 40
_MAX_FILE_BYTES = 64 * 1024
_MAX_TOTAL_BYTES = 512 * 1024
_ALLOWED_EXTS = (".cs", ".md", ".txt", ".json", ".asmdef")
_ALLOWED_ROOTS = ("Assets/", "ProjectSettings/", "Packages/")
_UNITY_VERSION = "2022.3.45f1"  # Unity 2022.3 LTS

_HONESTY_LINES = (
    "This project was generated by an AI and has NOT been compiled "
    "or tested in Unity. Art is placeholder (code-drawn primitives) "
    "unless you add your own assets.")

# Bound by app.py via bind_app (the visitor-history reader the
# packaging step uses to lift the exact approved files out of the
# visitor's own thread — same dep as og_github).
_deps: Dict = {}


def bind_app(deps):
    _deps.update(deps)


def _pro_url() -> str:
    base = os.getenv("OG_PUBLIC_URL", "https://og-ai-service.onrender.com")
    return base.rstrip("/") + "/pro"


# --- Pending build state (approval-gate state) --------------------------------
# One pending Unity build per visitor, process memory, hard expiry —
# the Round 14 pending-draft shape with one more stage.

_pending_builds: Dict[str, Dict] = {}
_pending_lock = threading.Lock()


def _set_pending(uid: str, state: Dict):
    state = dict(state)
    state["created"] = time.time()
    with _pending_lock:
        _pending_builds[uid] = state


def _get_pending(uid: str) -> Optional[Dict]:
    if not uid:
        return None
    with _pending_lock:
        state = _pending_builds.get(uid)
        if state and time.time() - float(state.get("created", 0)) \
                > _PENDING_TTL:
            del _pending_builds[uid]
            return None
        return dict(state) if state else None


def _clear_pending(uid: str):
    with _pending_lock:
        _pending_builds.pop(uid, None)


# --- Intent parsing -------------------------------------------------------------
# Deliberately narrow: a Unity ask needs the word "unity" plus a
# build verb (or want/give phrasing). Questions ABOUT Unity ("what
# is unity", "unity vs unreal") match nothing and flow to normal
# chat exactly as before.

_BUILD_VERB = (r"(?:make|build|create|generate|code|write|design|"
               r"develop)")
_ASK_RES = (
    r"\b" + _BUILD_VERB + r"\b[^.?!]{0,60}\bunity\b",
    r"\bunity\b[^.?!]{0,40}\b(game|project|app|prototype)\b[^.?!]{0,30}"
    r"\b" + _BUILD_VERB + r"\b",
    r"\b(?:i want|i need|give me|get me)\b[^.?!]{0,40}\bunity\b",
    r"\b" + _BUILD_VERB + r"\b[^.?!]{0,30}\ba unity\b",
)
_APPROVE_RE = re.compile(
    r"^\W*(yes|yeah|yep|yup|approve|approved|go ahead|do it|ship it"
    r"|confirm|ok|okay|package it|sounds good|let'?s go)\b")
_DECLINE_RE = re.compile(
    r"^\W*(no|nope|nah|cancel|scrap|discard|never ?mind|stop|don'?t"
    r"|do not)\b")
_REVISE_MARKERS = (
    "change", "add", "remove", "fix", "make", "faster", "slower",
    "bigger", "smaller", "instead", "replace", "update", "rename",
    "color", "colour", "speed", "jump", "also", "more", "less",
    "tweak", "adjust", "different", "increase", "decrease", "swap",
    "switch", "rather", "prefer", "but",
)
_PLAN_TWEAK_MARKERS = (
    "change", "add", "remove", "instead", "switch", "rather",
    "prefer", "make it", "turn it", "2d", "3d", "drop",
)


def _has_markers(low: str, markers) -> bool:
    return any(m in low for m in markers)


def parse_unity_intent(message: str) -> Optional[Dict]:
    """A fresh Unity build ask, or None."""
    low = " " + re.sub(r"\s+", " ", str(message).lower()).strip() + " "
    for pattern in _ASK_RES:
        if re.search(pattern, low):
            return {"kind": "ask", "request": str(message).strip()}
    return None


def _claim_job(message: str, uid: str) -> Optional[Dict]:
    """What this message means for the Unity maker, given the
    visitor's pending state. Approvals/declines only count against
    a live pending build; change requests only claim when they
    carry change language, so unrelated chat is never hijacked."""
    low = " " + re.sub(r"\s+", " ", str(message).lower()).strip() + " "
    trimmed = low.strip()
    pending = _get_pending(uid)
    fresh = parse_unity_intent(message)

    if pending is None:
        return fresh

    stage = pending.get("stage", "")
    decline = bool(_DECLINE_RE.match(trimmed))
    approve = bool(_APPROVE_RE.match(trimmed))
    revise = _has_markers(trimmed, _REVISE_MARKERS)

    if stage == "plan":
        if decline and not revise:
            return {"kind": "plan_decline"}
        if fresh:
            return fresh
        if approve and not _has_markers(trimmed, _PLAN_TWEAK_MARKERS):
            return {"kind": "plan_approve"}
        if _has_markers(trimmed, _PLAN_TWEAK_MARKERS):
            return {"kind": "plan_revise"}
        # New topic: the plan is abandoned, chat flows on untouched.
        _clear_pending(uid)
        return None

    if stage == "preview":
        if decline and not revise:
            return {"kind": "preview_decline"}
        if fresh:
            return fresh
        if approve and not revise:
            return {"kind": "preview_approve"}
        if revise:
            return {"kind": "revise"}
        return None  # unrelated chat; the draft stays parked

    if stage == "done":
        if fresh:
            return fresh
        if revise or "unity" in trimmed:
            return {"kind": "revise"}
        return None

    return fresh


# --- Instruction results (the seam's {title, body, href} shape) -----------------

def _result(tag: str, title: str, body: str, href: str = "") -> list:
    return [{"title": title, "body": f"[{tag}] " + body, "href": href}]


def _plan_body(request: str, revised: bool = False) -> list:
    step = ("The visitor tweaked the plan for the Unity project "
            "they asked for. Present the REVISED plan only — no "
            "code yet." if revised else
            "The visitor asked you to build them a Unity project. "
            "Present a plain-language PLAN only — no code yet.")
    body = (
        f"{step} Their ask: \"{request}\"\n\n"
        "The plan, in your own voice but covering exactly this: "
        "(1) what the game/app IS in one or two lines; (2) the "
        "pieces you'll make — the handful of C# scripts and what "
        "each one does; (3) how it plays / the controls; (4) what "
        "is placeholder: all art is code-drawn primitives (cubes, "
        "spheres, colors) — no real models or textures; (5) the "
        "honest note that you generate the project files but "
        "cannot compile or test in Unity — they'll open it in "
        "Unity 2022.3 LTS themselves.\n\n"
        "End with this line, word for word: Reply YES and I'll "
        "build it — or tell me what to change in the plan.")
    return _result("UNITY-MAKER: PLAN-REVISED" if revised
                   else "UNITY-MAKER: PLAN", "🎮 Unity maker — plan",
                   body)


def _generate_body(request: str, change: str = "") -> list:
    change_line = (
        f"Apply this change the visitor asked for: \"{change}\" — "
        "regenerate the ENTIRE project with it in." if change else
        "Generate the project from the approved plan.")
    body = (
        f"{change_line} The original ask: \"{request}\"\n\n"
        "Output the COMPLETE project NOW, in exactly this format "
        "and nothing else around it except the preview at the "
        "end:\n"
        "First line: === PROJECT: <a short project name> ===\n"
        "Then for EVERY file, exactly:\n"
        "=== FILE: <path> ===\n"
        "<the full file content>\n"
        "=== END FILE ===\n\n"
        "Rules: paths only under Assets/, ProjectSettings/ or "
        "Packages/; C# scripts (.cs) are plain Unity 2022.3 code, "
        "self-contained, no external packages, no downloads; "
        "include ONE bootstrap script that builds the scene in "
        "code at runtime (there is no .unity scene file — the "
        "user just presses Play); art is code-drawn primitives "
        "only; keep it compact — at most 8 files, each script "
        "tight and complete, never a sketch or a TODO.\n\n"
        "After the last === END FILE ===, present the preview in "
        "exactly this shape:\n"
        "📦 PREVIEW — <the project name>\n"
        "One line per file: its path\n"
        "Then this honesty note, in substance word for word: "
        + _HONESTY_LINES + "\n"
        "Then this closing line, word for word: Reply YES to "
        "package it into a downloadable ZIP — or tell me what "
        "to change.")
    tag = "UNITY-MAKER: REVISE" if change else "UNITY-MAKER: GENERATE"
    return _result(tag, "🎮 Unity maker — build", body)


def _declined_body(what: str) -> list:
    body = (f"The visitor said NO to the Unity {what}. It is "
            "SCRAPPED — nothing was built or packaged and nothing "
            "was charged. Confirm that to them in persona, briefly, "
            "and let them know they can ask for a different build "
            "any time.")
    return _result("UNITY-MAKER: DECLINED", "🎮 Unity maker — scrapped",
                   body)


def _cap_body(left_note: str) -> list:
    body = (f"The visitor wants a Unity project built, but they've "
            f"used up today's Unity project allowance for their "
            f"plan ({left_note}). Do NOT plan or build anything. "
            f"Tell them plainly, in persona, that the allowance "
            f"resets tomorrow — or that higher plans build more: "
            f"{_pro_url()}")
    return _result("UNITY-MAKER: CAP", "🎮 Unity maker — daily cap",
                   body, _pro_url())


# --- File-block extraction + validation ------------------------------------------

_FILE_BLOCK_RE = re.compile(
    r"^===\s*FILE:\s*(.+?)\s*===\s*$\n(.*?)^===\s*END FILE\s*===\s*$",
    re.S | re.M)
_PROJECT_RE = re.compile(r"===\s*PROJECT:\s*(.+?)\s*===", re.I)


def _extract_generation(uid: str):
    """Lift the latest generation out of the visitor's own thread:
    the newest assistant message carrying FILE blocks. Returns
    (project_name, {path: content}) or (None, {})."""
    load_history = _deps.get("load_history")
    if load_history is None:
        return None, {}
    try:
        history = load_history(uid)
    except Exception as e:
        logger.warning(f"Unity history read failed: {e}")
        return None, {}
    for entry in reversed(history or []):
        if not isinstance(entry, dict) \
                or entry.get("role") != "assistant":
            continue
        text = str(entry.get("content", ""))
        if "=== FILE:" not in text:
            continue
        files = {}
        for m in _FILE_BLOCK_RE.finditer(text):
            files[m.group(1).strip()] = m.group(2)
        if not files:
            return None, {}
        name = None
        m_name = _PROJECT_RE.search(text)
        if m_name:
            name = re.sub(r"[^\w\- ]+", "", m_name.group(1)).strip()[:60]
        return name or None, files
    return None, {}


def _sanitize_path(raw: str) -> Optional[str]:
    """A safe project-relative path, or None when the file must be
    dropped: no traversal, no absolute paths, allowlisted roots
    and extensions only."""
    path = str(raw or "").strip().replace("\\", "/")
    path = path.lstrip("/")
    if not path or len(path) > 200:
        return None
    parts = path.split("/")
    if any(p in ("", ".", "..") for p in parts):
        return None
    if not path.lower().endswith(_ALLOWED_EXTS):
        return None
    if path == "README.md":
        return path
    if not any(path.startswith(root) for root in _ALLOWED_ROOTS):
        return None
    return path


def _validate_files(raw_files: Dict) -> Optional[Dict]:
    """Sanitize + cap the extracted draft. Individual bad files
    are dropped; returns the clean {path: content} or None when
    nothing valid remains or the total-size cap is breached."""
    clean: Dict[str, str] = {}
    total = 0
    for raw_path, content in raw_files.items():
        path = _sanitize_path(raw_path)
        if path is None or path in clean:
            continue
        data = str(content).encode("utf-8")
        if len(data) > _MAX_FILE_BYTES:
            continue
        clean[path] = str(content)
        total += len(data)
        if len(clean) > _MAX_FILES or total > _MAX_TOTAL_BYTES:
            return None
    return clean or None


# --- Packaging ---------------------------------------------------------------------

def _readme_text(name: str, files: Dict) -> str:
    listing = "\n".join(
        f"- {p} ({len(c.encode('utf-8'))} bytes)"
        for p, c in sorted(files.items()))
    return (
        f"# {name}\n\n"
        "Generated by OG AI (the OG Unity maker), from a chat "
        "request, and approved by the requester before packaging.\n\n"
        "## Honesty note\n\n"
        + _HONESTY_LINES + "\n\n"
        "## Open it in Unity\n\n"
        "1. Install Unity Hub and Unity 2022.3 LTS (this project "
        "targets Unity 2022.3 LTS — see "
        "ProjectSettings/ProjectVersion.txt).\n"
        "2. Unzip this file and open the unzipped folder in "
        "Unity Hub (Open -> Add project from disk).\n"
        "3. Let Unity import. There is no prebuilt scene file: "
        "the bootstrap script under Assets/Scripts builds the "
        "scene in code — create an empty scene (or open any "
        "scene), and press Play; the bootstrap runs on load. If "
        "the README inside Assets says otherwise, follow the "
        "bootstrap script's own header comment.\n"
        "4. Swap the placeholder primitives for your own art "
        "when you're ready — the scripts mark the spots.\n\n"
        "## Files\n\n" + listing + "\n")


def _sweep_old_zips():
    try:
        now = time.time()
        for fname in os.listdir(UNITY_STORE_DIR):
            if not fname.endswith(".zip"):
                continue
            fpath = os.path.join(UNITY_STORE_DIR, fname)
            if now - os.path.getmtime(fpath) > _ZIP_TTL:
                try:
                    os.remove(fpath)
                    meta = fpath[:-4] + ".json"
                    if os.path.exists(meta):
                        os.remove(meta)
                except OSError:
                    pass
    except OSError:
        pass


def _package(uid: str, name: str, files: Dict) -> Optional[Dict]:
    """Zip the validated draft (module README + guaranteed project
    files). Returns {id, filename, size, files} or None."""
    files = dict(files)
    files.pop("README.md", None)
    if "ProjectSettings/ProjectVersion.txt" not in files:
        files["ProjectSettings/ProjectVersion.txt"] = (
            f"m_EditorVersion: {_UNITY_VERSION}\n"
            f"m_EditorVersionWithRevision: {_UNITY_VERSION}\n")
    if "Packages/manifest.json" not in files:
        files["Packages/manifest.json"] = (
            '{\n  "dependencies": {\n    "com.unity.ugui": "1.0.0"\n'
            "  }\n}\n")
    files["README.md"] = _readme_text(name, files)
    try:
        os.makedirs(UNITY_STORE_DIR, exist_ok=True)
        _sweep_old_zips()
        build_id = uuid.uuid4().hex
        slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")[:40] \
            or "unity-project"
        filename = f"{slug}.zip"
        zpath = os.path.join(UNITY_STORE_DIR, build_id + ".zip")
        with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as zf:
            for path in sorted(files):
                zf.writestr(path, files[path])
        import json
        meta = {"uid": uid, "name": name, "filename": filename,
                "created": datetime.now(timezone.utc).isoformat(),
                "files": sorted(files)}
        with open(os.path.join(UNITY_STORE_DIR, build_id + ".json"),
                  "w") as f:
            json.dump(meta, f)
        return {"id": build_id, "filename": filename,
                "size": os.path.getsize(zpath), "files": sorted(files)}
    except Exception as e:
        logger.warning(f"Unity packaging failed: {e}")
        return None


# --- Execution -----------------------------------------------------------------------

def unity_results(job, message, uid, consume_unity, unity_left):
    """Run one claimed Unity job. Returns web_search-shaped results
    (plan / generation / revision instructions, or the module's own
    packaging outcome), or None on a true miss so the caller falls
    through to the previous search untouched. Only a successful
    package spends a unity unit — via app.py's consume_unity."""
    if not job or not uid:
        return None
    kind = job.get("kind", "")

    if kind == "ask":
        left = None
        try:
            left = unity_left(uid) if unity_left else None
        except Exception as e:
            logger.warning(f"Unity cap check failed: {e}")
        if left is not None and left <= 0:
            return _cap_body("0 left today")
        _set_pending(uid, {"stage": "plan",
                            "request": job.get("request", "")})
        return _plan_body(job.get("request", ""))

    pending = _get_pending(uid)
    if pending is None:
        return None  # expired between claim and execution — not ours
    request = pending.get("request", "")

    if kind == "plan_decline":
        _clear_pending(uid)
        return _declined_body("plan")

    if kind == "preview_decline":
        _clear_pending(uid)
        return _declined_body("draft")

    if kind == "plan_revise":
        return _plan_body(request, revised=True)

    if kind == "plan_approve":
        _set_pending(uid, {"stage": "preview", "request": request})
        return _generate_body(request)

    if kind == "revise":
        _set_pending(uid, {"stage": "preview", "request": request,
                           "name": pending.get("name", "")})
        return _generate_body(request, change=str(message).strip())

    if kind == "preview_approve":
        name, raw_files = _extract_generation(uid)
        files = _validate_files(raw_files) if raw_files else None
        if not files:
            _clear_pending(uid)
            body = (
                "The visitor approved the Unity draft, but OG "
                "could NOT package it: the generated files in the "
                "thread didn't pass validation (missing, unsafe "
                "paths, or over the size caps). NOTHING was "
                "packaged and NOTHING was charged. Tell them "
                "plainly, in persona, and invite them to ask for "
                "the build again so a fresh draft is generated.")
            return _result("UNITY-MAKER: PACKAGE-FAILED",
                           "🎮 Unity maker — packaging stopped", body)
        name = name or pending.get("name") or "Unity Project"
        packed = _package(uid, name, files)
        if packed is None:
            _clear_pending(uid)
            body = (
                "The visitor approved the Unity draft, but the "
                "ZIP itself failed to build. NOTHING was packaged "
                "and NOTHING was charged. Tell them plainly, in "
                "persona, and invite them to ask again.")
            return _result("UNITY-MAKER: PACKAGE-FAILED",
                           "🎮 Unity maker — packaging stopped", body)
        spent = True
        if consume_unity is not None:
            try:
                spent = bool(consume_unity(uid))
            except Exception as e:
                logger.warning(f"Unity consume failed: {e}")
                spent = False
        if not spent:
            # Cap raced us — remove the ZIP, charge nothing, and
            # say so (the unit is only ever spent on success).
            try:
                os.remove(os.path.join(
                    UNITY_STORE_DIR, packed["id"] + ".zip"))
                os.remove(os.path.join(
                    UNITY_STORE_DIR, packed["id"] + ".json"))
            except OSError:
                pass
            _clear_pending(uid)
            return _cap_body("the last unit just went to another "
                             "build")
        _set_pending(uid, {"stage": "done", "request": request,
                           "name": name, "zip_id": packed["id"]})
        link = f"/unity/download/{packed['id']}"
        listing = ", ".join(packed["files"])
        body = (
            f"DONE — the Unity project the visitor approved is "
            f"PACKAGED: \"{name}\" ({len(packed['files'])} files, "
            f"{packed['size']} bytes zipped). Files: {listing}. "
            f"The download link is {link} — give them that exact "
            f"link, in persona. It works for 24 hours and only "
            f"from their browser. Remind them briefly: unzip, "
            f"open the folder in Unity Hub with Unity 2022.3 LTS, "
            f"press Play — and that it was AI-generated and not "
            f"compiled or tested, art is placeholder. If they "
            f"want changes after trying it, tell them to just ask "
            f"— fixes go through the same preview + YES flow and "
            f"ship as a new ZIP.")
        return _result("UNITY-MAKER: PACKAGED",
                       "🎮 Unity maker — packaged", body, link)

    return None


# ---------------------------------------------------------------------------
# The seam (app.py installs this LAST, after Rounds 3/4/6/9/10/12/13/14/15)
# ---------------------------------------------------------------------------

# The Unity job parsed for the exchange currently being processed.
# All chat processing is serialized under app.py's _memory_lock, so
# a single slot is safe — the same reasoning as app.py's own slots.
_pending = {"job": None, "message": ""}


def install_unity_tools(agent_instance, get_uid, consume_unity,
                        unity_left):
    """Wrap the agent's detect_intent + web_search hooks so Unity
    build asks and the approval flow ride the established seam.
    get_uid() returns the current visitor's uid; consume_unity(uid)
    spends one unit of the per-tier unity cap (False at cap);
    unity_left(uid) reports units left today. Claimed jobs also
    clear needs_code_generation — the agent's own code generator
    would otherwise hijack "make me a ..." asks before the search
    seam ever fires. Non-Unity messages pass through untouched.
    Persona files never touched."""
    if getattr(agent_instance, "_og_unity_installed", False):
        return
    prev_detect = getattr(agent_instance, "detect_intent", None)
    prev_search = getattr(agent_instance, "web_search", None)
    if prev_detect is None or prev_search is None:
        return

    def detect_wrapped(message):
        intent = prev_detect(message)
        _pending["job"] = None
        _pending["message"] = ""
        try:
            uid = get_uid()
            job = _claim_job(str(message), uid) if uid else None
            if job:
                _pending["job"] = job
                _pending["message"] = str(message)
                if isinstance(intent, dict):
                    intent["needs_code_generation"] = False
                    if not intent.get("needs_web_search"):
                        intent["needs_web_search"] = True
                        intent["search_query"] = str(message).strip()
        except Exception as e:
            logger.warning(f"Unity trigger check failed: {e}")
            _pending["job"] = None
        return intent

    def search_wrapped(query, num_results=5):
        job = _pending.get("job")
        message = _pending.get("message", "")
        _pending["job"] = None
        _pending["message"] = ""
        if job:
            try:
                results = unity_results(
                    job, message, get_uid(), consume_unity,
                    unity_left)
            except Exception as e:
                logger.warning(f"Unity job failed: {e}")
                results = None
            if results:
                return results[: max(1, num_results)]
        return prev_search(query, num_results)

    agent_instance.detect_intent = detect_wrapped
    agent_instance.web_search = search_wrapped
    agent_instance._og_unity_installed = True


# --- Download route (live) ------------------------------------------------------

def register_unity_routes(app):
    """Attach GET /unity/download/<id> — the packaged ZIP, served
    only to the visitor who owns it (their ogai_uid cookie), only
    inside the 24 h retention window."""

    @app.get("/unity/download/{build_id}")
    async def unity_download(build_id: str, raw_request: Request):
        if not re.fullmatch(r"[0-9a-f]{32}", build_id or ""):
            raise HTTPException(status_code=404, detail="Not found")
        zpath = os.path.join(UNITY_STORE_DIR, build_id + ".zip")
        mpath = os.path.join(UNITY_STORE_DIR, build_id + ".json")
        if not os.path.exists(zpath) or not os.path.exists(mpath):
            raise HTTPException(status_code=404, detail="Not found")
        if time.time() - os.path.getmtime(zpath) > _ZIP_TTL:
            raise HTTPException(status_code=404, detail="Not found")
        import json
        try:
            with open(mpath) as f:
                meta = json.load(f)
        except Exception:
            raise HTTPException(status_code=404, detail="Not found")
        uid = raw_request.cookies.get("ogai_uid")
        if not uid or meta.get("uid") != uid:
            raise HTTPException(status_code=404, detail="Not found")
        return FileResponse(
            zpath, media_type="application/zip",
            filename=meta.get("filename", "unity-project.zip"))
